
version: 2

sources:
  - name: staging
    database: sf-crime-76032
    schema: sf_crime_data_all

    tables:
      - name: external_incident_data

models:
  - name: staging_incident_data
    description: >
      one two theree
    
    columns:
      - name: row_id
        description: Primary key for this table.
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: incident_datetime
        description: Date and time the incident occurred.
      - name: incident_date
        description: Date the incident occurred.
      - name: incident_time
        description: Time the incident occurred.
      - name: incident_year
        description: Year the incident occurred.
      - name: incident_day_of_week
        description: Day of the week the incident occurred.
      - name: incident_id
        description: >
          System generated ID for incident reports.  Incident ID and Incident number uniquely
          identify reports.
      - name: incident_number
        description: >
          See Incident ID; used when referencing cases and report documents.  Number used in the report;
          sometimes interchangeably with case number. Number used to reference cases and report documents.
      - name: incident_code
        description: >
          Incident codes are the system codes to describe a type of incident.  A single incident report
          can have one or more incident types associated. In those cases, you will see multiple rows
          representing a unique combination of the incident ID and incident code.
      - name: incident_category
        description: >
          A category mapped on to the incident code used in statistics and reporting. Mappings provided by
          the Crime Analysis Unit of the Police Department.
      - name: incident_subcategory
        description: >
          A subcategory mapped to the incident code that is used for statistics and reporting. Mappings
          provided by the Crime Analysis Unit of the Police Department.
      - name: incident_description
        description: Description of the incident that corresponds to the incident code.
      - name: report_datetime
        description: Date and time the report was filed.
      - name: report_type_code
        description: System code for report types; having the corresponding descriptions within the dataset.
      - name: report_type_description
        description: >
          Description of the report type; possible values:
            * Initial
            * Initial Supplement
            * Vehicle Initial
            * Vehicle Supplement
            * Coplogic Initial
            * Coplogic Supplement
      - name: resolution
        description: >
          Resolution of the incident at the time of the report.  Possible values:
            * Cite or Arrest Adult
            * Cite or Arrest Juvenile
            * Exceptional Adult
            * Exceptional Juvenile
            * Open or Active
            * Unfounded
          
          Note, once a report is filed, the resolution will not change.  Status changes and/or updates
          must be provided using a Supplemental Report.
          * Incidents identifying juvenile information are not included in this dataset.  See Juvenile
            Data section for more information.
      - name: cad_number
        description: >
          The Computer Aided Dispatch (CAD) is the system used by the Department of Emergency Management (DEM) 
          to dispatch officers and other public safety personnel. CAD Numbers are assigned by the DEM system and 
          linked to relevant incident reports (Incident Number). Not all Incidents will have a CAD Number. 
          Those filed online via Coplogic (refer to “Filed Online” field) and others not filed through the 
          DEM system will not have CAD Numbers.
      - name: intersection
        description: >
          The two or more street names that intersect closest to the original incident separated by a 
          backward slash (\).  Note, the possible intersections will only include those that satisfy the
          privacy controls.
      - name: cnn
        description: >
          Unique identifier of the intersection for reference back to other related
          basemap datasets.
          For more on the Centerline Node Network, see https://datasf.gitbook.io/draft-publishing-standards/standard-reference-data/basemap/street-centerlines-nodes
      - name: police_district
        description: >
          The police district where the incident occurred. District boundaries can be reviewed in the link
          below. Please note this field is entered by officers and not based on the point.  Reference here:
          https://data.sfgov.org/d/wkhw-cjsf
        tests:
          - accepted_values:
              values: "{{ var('police_district_values') }}"
              severity: warn
      - name: analysis_neighborhood
        description: >
          This field is used to identify the neighborhood where each incident occurs. Neighborhoods and boundaries
          are defined by the Department of Public Health and the Mayor's Office of Housing and Community Development.
          Please reference the link below for additional info: https://data.sfgov.org/d/p5b7-5n3h.
          Please note this boundary is assigned based on the intersection, it may differ from the boundary the 
          incident actually occurred within.
      - name: supervisor_district
        description: >
          There are 11 members elected to the Board of Supervisors in San Francisco, each representing a 
          geographic district. The Board of Supervisors is the legislative body for San Francisco. The 
          districts are numbered 1 through 11. Please reference the link below for additional info:
          https://data.sfgov.org/d/8nkz-x4ny. Please note this boundary is assigned based on the intersection, 
          it may differ from the boundary the incident actually occurred within.
        tests:
          - accepted_values:
              values: "{{ var('supervisor_district_values') }}"
              severity: warn
              quote: false
      - name: latitude
        description: The latitude coordinate in WGS84; spatial reference is EPSG:4326.
      - name: longitude
        description: The longitude coordinate in WGS84; spatial reference is EPSG:4326.
      - name: point
        description: Geolocation in OGC WKT format (e.g., POINT(37.4, -122.3))
      - name: filed_online
        description: >
          Non- emergency police reports can be filed online by members of the public using SFPD’s self-service
          reporting system called Coplogic Values in this field will be “TRUE” if Coplogic was used to file the 
          report. Please reference the link below for additional info: (http://sanfranciscopolice.org/reports).
